### PR TITLE
[cloud-init] use `snap` and `write-files` modules

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Based on our discussion about egmde-confined-desktop's configure hook, this doesn't currently work. Correct?

**Comment by Saviq** [comment]
It doesn't install egmde-confined-desktop, the rest works.

**Comment by AlanGriffiths** [comment]
> It doesn't install egmde-confined-desktop, the rest works.

Right. It doesn't work. ;)

**Comment by AlanGriffiths** [comment]
@Saviq this should fix it right?

https://github.com/MirServer/egmde-confined-desktop/pull/22

**Comment by AlanGriffiths** [comment]
As this doesn't work, and we're not landing the "fix" to egmde-confined-desktop no point in having it here.

**Pull request closed without merging**
